apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
