apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.dns.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        {{ .Values.dns.provider }}:
          email: {{ .Values.dns.email }}
          apiTokenSecretRef:
            name: dns-api-token
            key: api-token
      selector:
        dnsZones:
          - {{ .Values.dns.zone }}
