ingress-nginx:
  controller:
    hostPort:
      enabled: true
    kind: DaemonSet
    metrics:
      enabled: true
    extraArgs:
      default-ssl-certificate: "nginx/default-ssl-certificate"
      enable-ssl-passthrough: true
    resources:
      limits:
        cpu: 100m
        memory: 90Mi
      requests:
        cpu: 100m
        memory: 90Mi