apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --source=ingress
        - --domain-filter={{ .Values.dns.zone }}
        - --provider={{ .Values.dns.provider }}
        env:
        - name: CF_API_KEY
          value: {{ .Values.dns.user.key }}
        - name: CF_API_EMAIL
          value: {{ .Values.dns.user.name }}