apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.org.project }}
  source:
    path: root-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - ../global-values/argo.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
