apiVersion: v2
name: local-lb
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: metallb
  repository: https://metallb.universe.tf
  version: 0.13.7