ingress-nginx:
  controller:
    hostPort:
      enabled: true
    kind: DaemonSet
    metrics:
      enabled: true
    #extraArgs:
    #  default-ssl-certificate: "argocd/argocd-tls-cert"
    #  enable-ssl-passthrough: true
    resources:
      limits:
        cpu: 1000m
        memory: 900Mi
      requests:
        cpu: 1000m
        memory: 900Mi
