apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.1
        args:
        - --source=ingress
        - --source=service
        - --domain-filter={{ .Values.dns.zone }}
        - --provider={{ .Values.dns.provider }}
        - --log-level=debug
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dns-api-token
              key: api-token
              optional: false
