apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.13.11
