apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  project: {{ .Values.org.project }}
  source:
    path: apps/cert-manager
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - ../../global-values/dns.yaml
      - ../../local-files/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  