apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-lb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: metallb
  project: {{ .Values.org.project }}
  source:
    path: apps/local-lb
    repoURL: "git@github.com:sefs93/k8s-media.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  