apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-routes
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  project: {{ .Values.org.project }}
  source:
    path: apps/service-routes
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - ../../local-values/dns.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  