apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.org.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.org.project }}
  source:
    path: helm-guestbook
    repoURL: "https://github.com/argoproj/argocd-example-apps"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  