apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: transmission
  project: {{ .Values.org.project }}
  source:
    path: services/transmission
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
#    helm:
#      valueFiles:
#      - ../../global-values/dns.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  